//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumService
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnsverAnsver
    {
        public int Id { get; set; }
        public int AnsverId { get; set; }
        public string name { get; set; }
        public string text { get; set; }
        public System.DateTime date { get; set; }
        public int rating { get; set; }
        public string code { get; set; }
    }
}
