//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumService
{
    using System;
    using System.Collections.Generic;
    
    public partial class OneUser
    {
        public string name { get; set; }
        public string password { get; set; }
        public byte[] foto { get; set; }
        public Nullable<int> age { get; set; }
        public int rating { get; set; }
        public int ratingAnswers { get; set; }
        public int ratingQwery { get; set; }
        public string about { get; set; }
    }
}
